version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: development
    commit-message:
      prefix: 'build'
      prefix-development: 'build'
      include: "scope"
    schedule:
      interval: "daily"
    groups:
      python:
        patterns:
          - "*"
    ignore:
      - dependency-name: "pydantic"
        versions: [ ">=2" ]
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: 'ci'
      include: "scope"
    schedule:
      interval: "daily"
    groups:
      github-actions:
        patterns:
          - "*"
    ignore:
      - dependency-name: "zricethezav/gitleaks-action"
