FROM python:latest

RUN pip install pipenv

WORKDIR /sdk

COPY Pipfile Pipfile.lock ./

RUN pipenv install --deploy --ignore-pipfile --dev

COPY . .

ENTRYPOINT ["pipenv", "run"]

CMD ["echo", "\"Enter Command(Read DEVELOPMENT.md)\""]
