FROM python:latest

RUN pip install pipenv

WORKDIR /sdk

COPY Pipfile ./

RUN pipenv install --deploy --dev

COPY . .

ENTRYPOINT ["pipenv", "run"]

CMD ["echo", "\"Enter Command(Read DEVELOPMENT.md)\""]
