FROM python:alpine

WORKDIR /sdk

COPY req.txt req.txt
COPY req.dev.txt req.dev.txt

RUN pip install -r req.txt
RUN pip install -r req.dev.txt

COPY . .

CMD echo "Enter Command(Read DEVELOPMENT.md)"
