name: Release
on:
  push:
    branches:
      - feature/automated-release

jobs:
  bump:
    name: Bump Source Code
    if: "!contains(github.event.head_commit.message, 'bump')"
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Define Version Change
        uses: actions/github-script@v6
        id: define-bump-type
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const BUMP_TYPE = {
              Patch: 'patch',
              Minor: 'minor',
              Major: 'major'
            };
            
            try {
              const isMinor = context.payload.head_commit.message.toLowerCase().includes('feature');
            
              return isMinor ? BUMP_TYPE.Minor : BUMP_TYPE.Patch
            } catch (e) {
              console.error(e);
              return BUMP_TYPE.Patch;
            }

      - uses: actions/checkout@v3

      - name: "Build Changelog"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply Bump
        id: bump
        run: |
          docker build . -f Dockerfile.dev -t emnify/python-sdk
          docker run -v $(pwd):/sdk emnify/python-sdk bump2version patch --list >> $GITHUB_ENV

      - name: Commit New Version
        run: |
          echo "previous  ${{ env.current_version }}
          echo "current ${{ env.new_version }}
          echo ${{steps.build_changelog.outputs.changelog}}

