name: Release
on:
  push:
    branches:
      - main

jobs:
  bump:
    env:
      RELEASE_REPOSITORY: testpypi
      RELEASE_PACKAGE_NAME: emnify-sdk-test-beta
      RELEASE_PYPI_TOKEN: ${{secrets.PYPI_RELEASE_TOKEN}}
    name: Bump and Release
    # Skip circular workflow run
    if: "!contains(github.event.head_commit.message, '[Automated]')"
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}


      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          release_branches: master,main,feature/automated-release
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Apply Bump
        id: bump
        run: |
          docker build . -f Dockerfile.dev -t emnify/python-sdk
          docker run -v $(pwd):/sdk emnify/python-sdk bump2version patch --new-version=${{ steps.tag_version.outputs.new_version }} --list >> $GITHUB_ENV

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '[Automated] Version Bump from ${{ env.current_version }} to ${{ env.new_version }}'

      - name: Release and Publish Package
        run: |
          cat <<EOT >> .env
          TWINE_REPOSITORY=${{env.RELEASE_REPOSITORY}}
          TWINE_USERNAME=__token__
          TWINE_PASSWORD=${{env.RELEASE_PYPI_TOKEN}}
          PYPI_PACKAGE_NAME=${{env.RELEASE_PACKAGE_NAME}}
          EOT

          docker run --env-file=.env -v $(pwd):/sdk emnify/python-sdk python3 -m build
          docker run --env-file=.env -v $(pwd):/sdk emnify/python-sdk python3 -m twine upload dist/* 

