name: Release
on:
  push:
    branches:
      - feature/automated-release

jobs:
  bump:
    name: Bump Source Code
    if: "!contains(github.event.head_commit.message, 'bump')"
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Define Version Change
        uses: actions/github-script@v6
        id: define-bump-type
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const BUMP_TYPE = {
              Patch: 'patch',
              Minor: 'minor',
              Major: 'major'
            };
            
            try {
              const isMinor = context.payload.head_commit.message.toLowerCase().includes('feature');
            
              return isMinor ? BUMP_TYPE.Minor : BUMP_TYPE.Patch
            } catch (e) {
              console.error(e);
              return BUMP_TYPE.Patch;
            }
            

      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install -r req.txt

      - name: Apply Bump
        id: bump
        run: |
          bump2version ${{steps.define-bump-type.outputs.result}} --commit
            
          echo "${BUMPVERSION_CURRENT_VERSION}"
          echo $BUMPVERSION_NEW_VERSION
          
          echo "::set-output name=previous_version::$BUMPVERSION_CURRENT_VERSION"
          echo "::set-output name=current_version::$BUMPVERSION_NEW_VERSION"

      - name: Commit New Version
        run: |
          echo "previous ${{ steps.random-color-generator.outputs.previous_version }}"
          echo "current ${{ steps.random-color-generator.outputs.current_version }}"

