name: Documentation
on:
  push:
    branches:
      - main

jobs:
  documentation:
    # Prevent circular workflow run
    if: "!contains(github.event.pusher.name, 'emnify-gha')"
    name: Generate and publish Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3

      - name: Prepare doc-gen
        run: docker build . -f docs/Dockerfile.dev -t emnify/python-sdk-docs

      - name: Run doc-gen
        run: docker run -t -v $(pwd):/docs emnify/python-sdk-docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build_sphinx
