name: gitleaks

on: [push]

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: gitleaks
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: .gitleaks.toml
