name: gitleaks

on: [push]

jobs:
  gitleaks:
    # Skip circular workflow run
    if: "!contains(github.event.head_commit.message, '[Automated]')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: gitleaks
        uses: zricethezav/gitleaks-action@master
        with:
          config-path: .gitleaks.toml
