name: gitleaks

on: [push]

jobs:
  gitleaks:
    # Prevent circular workflow run
    if: "!contains(github.event.pusher.name, 'emnify-gha')"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: gitleaks
        uses: zricethezav/gitleaks-action@v1.6.0
        with:
          config-path: .gitleaks.toml
