name: Lint-Check
on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install ruff

      - name: Run check
        run: ruff check .