name: Unit-Tests
on:
  push:
    branches:
      - main
      # TODO: remove temporary credential
      - feature/sonarcloud-action
  pull_request:
      branches:
        - '*'

jobs:
  build:
    name: Run Unit-Tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r req.txt

      - name: Run tests
        run: pytest --cov-report=xml
      - name: Export SonarCloud Result
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage.xml
