name: Unit-tests
on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - '*'

jobs:
  test:
    # Skip circular workflow run
    if: "!contains(github.event.head_commit.message, '[Automated]')"
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r req.txt

      - name: Run tests
        run: pytest --cov=emnify --cov-report=xml --cov-branch
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
