name: Unit-Tests
on:
  push:
    branches:
      - main
  pull_request:
      branches:
        - '*'

jobs:
  test:
    # Prevent circular workflow run
    if: "!contains(github.event.pusher.name, 'emnify-gha')"
    name: Run Unit-Tests
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -r req.txt

      - name: Run tests
        run: pytest --cov=. --cov-report=xml
      - name: Export SonarCloud Result
        if: ${{ secrets && secrets.SONAR_TOKEN }}
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: sdk-coverage-result
          path: coverage.xml
